CREATE TABLE transfers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  from_customer VARCHAR(200) NOT NULL,
  to_customer VARCHAR(200) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  issue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);